nouns = {
  'a': ['abyss', 'angel', 'artifact', 'anomaly', 'algorithm', 'atmosphere', 'antenna'],
  'b': ['beacon', 'bubble', 'boundary', 'balance', 'butterfly', 'breeze', 'blossom'],
  'c': ['cosmos', 'catalyst', 'crystal', 'conundrum', 'cipher', 'cascade', 'crescendo'],
  'd': ['dimension', 'dynamo', 'dream', 'duality', 'dawn', 'dusk', 'divergence'],
  'e': ['echo', 'eternity', 'enigma', 'essence', 'evolution', 'eclipse', 'equilibrium'],
  'f': ['frequency', 'flux', 'fountain', 'fusion', 'fable', 'fantasy', 'form'],
  'g': ['galaxy', 'gravity', 'glimmer', 'glow', 'genesis', 'garden', 'groove'],
  'h': ['harmony', 'horizon', 'haze', 'hallucination', 'hologram', 'hypnosis', 'haven'],
  'i': ['infinity', 'illusion', 'insight', 'imagination', 'intuition', 'inception', 'impulse'],
  'j': ['juxtaposition', 'jubilation', 'jigsaw', 'journey', 'jolt', 'junction', 'jazz'],
  'k': ['kaleidoscope', 'karma', 'key', 'kinetic', 'kismet', 'kinesis', 'knight'],
  'l': ['labyrinth', 'light', 'luminescence', 'levitation', 'landscape', 'legacy', 'loop'],
  'm': ['manifold', 'matrix', 'mystery', 'mirage', 'metamorphosis', 'momentum', 'myth'],
  'n': ['nebula', 'nexus', 'nocturne', 'novelty', 'nirvana', 'numen', 'nucleus'],
  'o': ['oasis', 'odyssey', 'oracle', 'oscillation', 'origin', 'overture', 'oblivion'],
  'p': ['paradox', 'portal', 'pulse', 'pattern', 'phantom', 'prophecy', 'paragon'],
  'q': ['quasar', 'quantum', 'quintessence', 'quiver', 'quandary', 'quicksilver', 'quest'],
  'r': ['resonance', 'reverie', 'rhythm', 'radiance', 'reflection', 'rift', 'revelation'],
  's': ['symphony', 'spectrum', 'shadow', 'silhouette', 'solstice', 'serendipity', 'sanctuary'],
  't': ['transcendence', 'tesseract', 'twilight', 'tide', 'tempo', 'trance', 'threshold'],
  'u': ['universe', 'utopia', 'unity', 'umbra', 'uplift', 'ultra', 'undulation'],
  'v': ['vortex', 'vision', 'vibration', 'voyage', 'veil', 'vivid', 'vanguard'],
  'w': ['wavelength', 'whisper', 'wonder', 'wisdom', 'web', 'wind', 'wave'],
  'x': ['xenon', 'xanadu', 'x-ray', 'xenolith', 'xylem', 'xenogenesis', 'xylophone'],
  'y': ['yonder', 'yearning', 'yugen', 'yin', 'yang', 'yawn', 'yesteryear'],
  'z': ['zenith', 'zephyr', 'zone', 'zodiac', 'zigzag', 'zombie', 'zeppelin']
}